# Generated by Django 4.2.30 on 2026-08-30 17:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0003_alter_travelpost_notes'),
        ('packages', '0004_remove_packagerequest_weight_must_be_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(db_index=True, default=orders.models.generate_order_reference, max_length=20, unique=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('package_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='CONFIRMED', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=20)),
                ('package_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='packages.packagerequest')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payments.paymenttransaction')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='proposals.proposal')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_requester', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_traveler', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='travel.travelpost')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'delivery_status'], name='orders_orde_status_4a0ce1_idx'), models.Index(fields=['traveler', 'status'], name='orders_orde_travele_4c0ac1_idx'), models.Index(fields=['requester', 'status'], name='orders_orde_request_c36d54_idx')],
            },
        ),
    ]
