# Generated by Django 4.2.30 on 2026-08-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country_code', 'city'], name='travel_loca_country_91cd33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'state_province', 'country_code')},
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['status', 'departure_date'], name='travel_trav_status_7646d2_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['origin', 'destination'], name='travel_trav_origin__86adf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='travelpost',
            constraint=models.CheckConstraint(check=models.Q(('capacity_kg__gt', 0)), name='capacity_must_be_positive'),
        ),
    ]
