# Generated by Django 4.2.30 on 2026-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
