# Generated by Django 4.2.30 on 2026-08-25 17:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_pickup_date', models.DateTimeField()),
                ('required_delivery_date', models.DateTimeField(db_index=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('DOC', 'Documents'), ('CLO', 'Clothing'), ('ELE', 'Electronics'), ('PER', 'Personal Items'), ('GFT', 'Gifts'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('MATCHING', 'Matching'), ('MATCHED', 'Matched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20)),
            ],
        ),
    ]
