# Generated by Django 4.2.30 on 2026-08-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='packagerequest',
            index=models.Index(fields=['status', 'required_delivery_date'], name='packages_pa_status_169445_idx'),
        ),
        migrations.AddIndex(
            model_name='packagerequest',
            index=models.Index(fields=['origin', 'destination'], name='packages_pa_origin__e059a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagerequest',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='weight_must_be_positive'),
        ),
    ]
