# Generated by Django 4.2.30 on 2026-08-30 17:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagerequest',
            name='weight_must_be_positive',
        ),
        migrations.RemoveField(
            model_name='packagerequest',
            name='requested_pickup_date',
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('MATCHED', 'Matched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AddConstraint(
            model_name='packagerequest',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='package_weight_must_be_positive'),
        ),
    ]
